name: Check USNs
on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [new-usn]

jobs:
  check-usns:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/usns/update

    - name: Get USN List
      run: |
        echo '[{"title":"USN-4744-1: OpenLDAP vulnerability","link":"https://ubuntu.com/security/notices/USN-4744-1","cves":[{"title":"CVE-2021-27212","link":"https://people.canonical.com/~ubuntu-security/cve/CVE-2021-27212","description":"In OpenLDAP through 2.4.57 and 2.5.x through 2.5.1alpha, an assertion failure in slapd can occur in the issuerAndThisUpdateCheck function via a crafted packet, resulting in a denial of service (daemon exit) via a short timestamp. This is related to schema_init.c and checkTime."}],"affected_packages":["apt"]}]' > full-usn-list
      # curl -sL --fail -u 'paketo-bot:${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}' \
      #   api.github.com/repos/paketo-buildpacks/stack-usns/contents/usns | \
      #   jq -r '.content' | base64 --decode > full-usn-list

    - name: Update USNs
      uses: paketo-buildpacks/stacks/actions/usn-update@main
      with:
        build_receipt: build-receipt
        run_receipt: run-receipt
        full_usn_list: full-usn-list
        relevant_usn_list: usns

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Add new USNs"
        pathspec: "usns"

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/usns/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Add new USNs"
        branch: automation/usns/update

