name: Trigger Release
on:
  push:
    branches: [ main ]
    paths: [ usns ]

jobs:
  trigger-releases:
    runs-on: ubuntu-18.04

    steps:
    - name: Trigger Release
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: paketo-buildpacks/stacks
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: new-base-usn
        payload: '{}'
